import { Bug, Hourglass, Kanban, List } from "lucide-react";

export const AVAILABLE_TAGS = [
  "Productivity",
  "AI",
  "Healthcare",
  "Edutech",
  "Fintech",
  "Web3",
  "Agents",
  "SaaS",
  "E-commerce",
  "Social Media",
  "Developer Tools",
  "Open Source",
  "Machine Learning",
  "Data Science",
  "Blockchain",
  "Crypto",
  "DeFi",
  "NFT",
  "Metaverse",
  "Gaming",
  "AR/VR",
  "Mobile App",
  "Web App",
  "Desktop App",
  "CLI",
  "API",
  "Library",
  "Framework",
  "CMS",
  "CRM",
  "Automation",
  "Cybersecurity",
  "Database",
  "Cloud",
  "DevOps",
  "Testing",
  "Monitoring",
  "Analytics",
  "Marketing",
  "SEO",
  "Content",
  "Design",
  "UX/UI",
  "Education",
  "Research",
  "Environment",
  "Sustainability",
  "Non-profit",
  "Community",
];

export const ROLES = [
  "frontend developer",
  "backend developer",
  "fullstack developer",
  "devops engineer",
  "site reliability engineer",
  "cloud engineer",
  "cloud architect",
  "data scientist",
  "machine learning engineer",
  "AI engineer",
  "mobile developer (iOS)",
  "mobile developer (Android)",
  "cross-platform mobile developer",
  "flutter developer",
  "react native developer",
  "game developer",
  "unity developer",
  "unreal engine developer",
  "embedded systems engineer",
  "hardware engineer",
  "robotics engineer",
  "AR/VR developer",
  "computer vision engineer",
  "blockchain developer",
  "solidity developer",
  "web3 developer",
  "cybersecurity engineer",
  "network engineer",
  "systems administrator",
  "database administrator",
  "QA engineer",
  "test automation engineer",
  "site reliability engineer",
  "API developer",
  "kubernetes administrator",
  "salesforce developer",
  "IoT engineer",
  "MLOps engineer",
  "CRM developer",
  "generative AI engineer",
  "UX/UI designer",
  "enterprise architect",
  "software architect",
];

export const PROJECT_STATUS = [
  "ideation",
  "validation",
  "development",
  "beta",
  "production",
  "scaling",
];

export const  TABS = [
  { id: "List", label: "List", icon: List },
  { id: "Kanban", label: "Kanban", icon: Kanban },
  { id: "Issues", label: "Issues", icon: Bug },
  { id: "Sprint", label: "Sprint", icon: Hourglass },
];


export const INVITE_LINK="http://localhost:3000/";
